Add application-profile icon
vrk-kpa/suomifi-icons pull request #69
Opened 2022-06-23 07:56 UTC by ketsappi

## Description

Adds new icon, application-profile.

## Release notes

- Add `application-profile` icon

2022-06-27 10:50 UTC, riitasointi requested changes

2022-06-27 10:50 UTC, riitasointi commented on src/baseIcons/application-profile.svg
> +</svg>
I think this file should follow the established naming convention: `icon-XXXXX.svg`

2022-06-27 11:58 UTC, ketsappi commented on src/baseIcons/application-profile.svg
> +</svg>
That is totally true. Good catch! Will fix this.

2022-06-27 12:04 UTC, ketsappi commented on src/baseIcons/application-profile.svg
> +</svg>
This fix is now done and available in this commit https://github.com/vrk-kpa/suomifi-icons/pull/69/commits/a1ad325031432da3d1f6f2db5d5ff83e1b0220bb

2022-06-28 12:58 UTC, riitasointi approved these changes
Looks good!

2022-06-29 07:35 UTC, merged